### ISSUE TITLE
Readme file

### ISSUE THREAD

**Issue by Kanchangk** [rthennan/ZerodhaWebsocket#1]
Hi,

Great job done, indeed. 
But going through the file, it's hard to understand which file does what and how DAS5 & DAS6 is related (or independent) sine there's little to none comments in the code and no steps to use the script. 

Can you please help with that?

Thanks.

**Comment by rthennan** [comment]
Hi @Kanchangk 

I had been making just incremental changes to the repo in the past two years, not focussing much on a new installation perspective.
But when I sat down last week to revamp the project to use one Zerodha API app (3000 instruments limit per connection), I realized how messed up it was for someone new to understand.

I couldn't even recognize and follow most of the code.
Apologies and thanks for spending time trying to understand the project.

I have revamped the project entirely, simplifying the flow and naming convention and adding comments wherever possible.

I am unsure if this is of any help to you. 
But I hope it at least helps others.
Closing this issue.
Please feel free to reopen if applicable.

Thanks
