### ISSUE TITLE
Conversion to candles

### ISSUE THREAD

**Issue by punksterlabs** [rthennan/ZerodhaWebsocket#2]
Hello, pretty cool project this - while this is not a bug, I couldn't figure out another way to communicate with you :)

I had a couple of Qs

- How do you convert these ticks to candlesticks currently?
- I see that something like timescale plugin has the ability to handle conversion to candles - does MariaDB have something inbuilt to deal with that?
- As a tickstorage system this is adequate - but once you want to run computations around candles and symbols - what might be a good architecture? Or do you believe the current architecture with a high enough IOPS can handle it?

Thanks

**Comment by rthennan** [comment]
Hi @punksterlabs 
I use MariaDB purely for storage.
I do all the computation outside using Python, mostly Pandas.
I [resample tick to candles in Pandas](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.resample.html) 
Example:
1. Define SQL query to get raw data for a specific period
```
indexRawQuery = f'''SELECT timestamp, price
                                FROM das_nse.{indexChosen} 
                                WHERE timestamp <= '{currDate} 15:30:00'
                                AND timestamp >= '{currDate} 09:15:00'
                                ORDER BY timestamp'''
```
2. Read this in Pandas
```
connection_string = f"mysql+mysqldb://{mySQLUser}:{mySQLPass}@{mySQLHost}:{mySQLPort}"    
engine = sqlalchemy.create_engine(connection_string)    
indexRawData = pd.read_sql(indexRawQuery, engine, index_col='timestamp')   
```
3. indexRawData is now tick. I can convert it to candle Sticks like so, where `resFreq` is the frequency. 10S, 30S, 1min,10min, etc. :
```
    indexOHLC = indexRawData.resample(resFreq).agg(
                open=('price', 'first'),
                high=('price', 'max'),
                low=('price', 'min'),
                close=('price', 'last')
            )
```

This works without issues in Live data as ticks, and in turn, OHLC will only be available for the present and past data, and you can navigate through the Dataframe as you wish.
But if you are focussing on the timestamp index, both for live and backtests, please bear in mind that the timestamp of the row will be the candle's open time and not the close time.

For example, the first candle's timestamp in the example query I have shown would be 09:15:00.
Assume you are working win resFreq='5min',  the OHLC candle would have been available only at 09:20:00.
The dataframe's index timestamp would be somewhat misleading and result in peeking/cheating if you are backtesting data as is.

I usually do a shift and dropna to avoid this.
`indexOHLC = indexOHLC.shift().dropna(inplace=True)`
